# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: rlespinasse/github-slug-action@v4
      -
        uses: actions/checkout@v3
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eunts/frwd:${{ env.GITHUB_REF_SLUG }}

  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref == 'refs/heads/master'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
